### ISSUE TITLE
Suboptimal QEMU build chosen for patch

### ISSUE THREAD

**Issue by Samuil1337** [Scrut1ny/Hypervisor-Phantom#9]
Hi Scrut1ny,

I was adding support for Archlinux to your script, when I noticed that you download the master branch of QEMU before patching it. I would suggest that we chose a stable release, because they are more tested/you are not downloading source with incomplete features. Also using older LTS stable versions like 8.2.x would be better as they are still getting security updates and fixes, but no feature updates, which are more likely to break the patch. 9.0.1 is also pretty buggy. I've seen a lot of people, me included, that can't do USB host passthrough on that version of QEMU without the VM crashing. I think that when we create the patch we should work on a stable release and right now the best one would be 8.2.5 imo.

Yours sincerely,
Samuil1337

**Comment by Scrut1ny** [comment]
I personally want to use Arch Linux, but I haven't made the switch yet because there's a lot to learn. I really really do want to switch though. Currently I just use Linux Mint xD. I've been wanting to add other distro support though badly, I just wouldn't know how to do it properly because I don't have enough experience with others. You would be a great help in completing the Arch section because I know a lot of users tend to use Arch when it comes to VFIO stuff.

Switching to a more stable release I do agree with, it's a lot of work messing with a master branch that's constantly being messed around with. If you believe the best stable version would be 8.2.5, than we shall switch. I'll work on the patch file once we've chosen the best stable release.
